services:
    bitbag_sylius_wishlist_plugin.serializer.csv_encoder:
        class: Symfony\Component\Serializer\Serializer
        arguments:
          0:
            - "@serializer.normalizer.object"
          1:
            - "@serializer.encoder.csv"
