services:
    app:
        container_name: app
        build:
            context: .
        environment:
            APP_ENV: "dev"
            DATABASE_URL: "mysql://root:mysql@mysql/sylius_%kernel.environment%?charset=utf8mb4"
#            DATABASE_URL: "pgsql://root:postgres@postgres/sylius_%kernel.environment%?charset=utf8" # When using postgres
            PHP_DATE_TIMEZONE: "Europe/Warsaw"
            MAILER_DSN: "smtp://mailhog:1025"
            # to enable step debugging, build with e.g. XDEBUG_MODE=debug, or set the below to "debug"
            XDEBUG_MODE: ${XDEBUG_MODE:-off}
            # to use xdebug, create a server named PHPSTORM in Settings > PHP > Servers
            PHP_IDE_CONFIG: "serverName=PHPSTORM"
        volumes:
            - ./:/app:delegated
            - ./.docker/php.ini:/etc/php8/php.ini:delegated
            - ./.docker/nginx.conf:/etc/nginx/nginx.conf:delegated
        ports:
            - "80:80"
        depends_on:
            - mysql
        networks:
            - sylius

    mysql:
        container_name: mysql
        image: mysql:8.0
        platform: linux/amd64
        environment:
            MYSQL_ROOT_PASSWORD: mysql
        ports:
            - ${MYSQL_PORT:-3306}:3306
        networks:
            - sylius

#    postgres:
#        image: postgres:14-alpine
#        environment:
#            POSTGRES_USER: root
#            POSTGRES_PASSWORD: postgres
#        ports:
#            - ${POSTGRES_PORT:-5432}:5432
#        networks:
#            - sylius

    mailhog:
        container_name: mailhog
        # do not use in production!
        image: mailhog/mailhog:latest
        environment:
            - MH_STORAGE=maildir
        # volumes:
        #   - ./docker/mailhog/maildir:/maildir:rw,delegated
        ports:
            - "${MAILHOG_PORT:-8025}:8025"
        networks:
            - sylius

networks:
    sylius:
        driver: bridge
