sylius_twig_hooks:
    hooks:
        'sylius_shop.product.show.content.info.summary.add_to_cart':
            submit:
                template: '@SyliusWishlistPlugin/Product/Show/_addToCart.html.twig'
