sylius_twig_hooks:
    hooks:
        'sylius_shop.product.show.content.info.summary':
            add_to_wishlist:
                template: '@SyliusWishlistPlugin/Common/_addToWishlist.html.twig'
                priority: 10
        'sylius_shop.product.show.content.info.summary.add_to_wishlist':
            add_to_wishlist:
                template: '@SyliusWishlistPlugin/Common/AddToWishlist/_button.html.twig'
