sylius_twig_hooks:
  hooks:
    'wishlist.cart':
      buttons:
        template: '@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/buttons.html.twig'
        priority: 300
      flashes:
        template: "@SyliusShop/shared/flashes.html.twig"
        priority: 200
      form:
        component: 'wishlist:form:cart'
        props:
          resource: '@=_context.wishlist'
          form: '@=_context.form'
          template: "@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/form.html.twig"
        priority: 100
      actions:
        template: '@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/actions.html.twig'
        priority: 0

    'wishlist.cart.buttons':
      add_another_wishlist:
        template: '@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/buttons/add_another_wishlist.html.twig'
        priority: 0

    'wishlist.cart.form':
      items:
        template: '@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/form/items.html.twig'
        priority: 0

    'wishlist.cart.actions':
      collective:
        template: '@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/actions/collective.html.twig'
        priority: 0

    'wishlist.cart.form.items':
      head:
        template: '@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/form/items/head.html.twig'
        priority: 100
      product:
        template: '@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/form/items/product.html.twig'
        priority: 0

    'wishlist.cart.form.items.product':
      body:
        component: 'wishlist:product'
        props:
          product: '@=_context.product'
          template: '@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/form/items/product/body.html.twig'
        priority: 0

    'wishlist.cart.form.items.head':
      remove:
        template: '@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/form/items/head/actions.html.twig'
        priority: 400
      variant:
        template: '@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/form/items/head/variant.html.twig'
        priority: 300
      unit_price:
        template: '@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/form/items/head/price.html.twig'
        priority: 200
      quantity:
        template: '@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/form/items/head/quantity.html.twig'
        priority: 100
      total:
        template: '@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/form/items/head/checkbox.html.twig'
        priority: 0

    'wishlist.cart.form.items.product.body':
      remove:
        template: '@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/form/items/product/body/actions.html.twig'
        priority: 400
      variant:
        component: 'wishlist:product:variant'
        props:
          product: '@=_context.product'
          template: '@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/form/items/product/body/variant.html.twig'
#        template: '@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/form/items/product/body/variant.html.twig'
        priority: 300
      unit_price:
        template: '@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/form/items/product/body/price.html.twig'
        priority: 200
      quantity:
        template: '@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/form/items/product/body/quantity.html.twig'
        priority: 100
      total:
        template: '@BitBagSyliusWishlistPlugin/Components/Wishlist/forms/cart/form/items/product/body/checkbox.html.twig'
        priority: 0
