sylius_twig_hooks:
    hooks:
        'sylius_shop.base.header.content':
            wishlist_header:
                template: "@BitBagSyliusWishlistPlugin/shop/wishlist_header.html.twig"
                priority: 150

# TODO find the right way to extend product box's content
#sylius.shop.product.index.box:
#            blocks:
#                content:
#                    template: "@BitBagSyliusWishlistPlugin/Product/Box/_content.html.twig"
#                    priority: 10
