sylius_twig_hooks:
    hooks:
        'sylius_shop.base.header.content':
            wishlist_header:
                template: '@SyliusWishlistPlugin/_wishlist_header.html.twig'
                priority: 150
